//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCompanySystem.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Page {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Page() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaterCompanySystem.Resourses.Page", typeof(Page).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllCustomerReport.
        /// </summary>
        public static string AllCustomerReport {
            get {
                return ResourceManager.GetString("AllCustomerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllEmployeeReport.
        /// </summary>
        public static string AllEmployeeReport {
            get {
                return ResourceManager.GetString("AllEmployeeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllSuplierStoreReport.
        /// </summary>
        public static string AllSuplierStoreReport {
            get {
                return ResourceManager.GetString("AllSuplierStoreReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllSuplierStoreReportWithType.
        /// </summary>
        public static string AllSuplierStoreReportWithType {
            get {
                return ResourceManager.GetString("AllSuplierStoreReportWithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alwance.
        /// </summary>
        public static string alwance {
            get {
                return ResourceManager.GetString("alwance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmountReportDate.
        /// </summary>
        public static string AmountReportDate {
            get {
                return ResourceManager.GetString("AmountReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmountReportTowDate.
        /// </summary>
        public static string AmountReportTowDate {
            get {
                return ResourceManager.GetString("AmountReportTowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string Areyousureyouwanttodeletethis {
            get {
                return ResourceManager.GetString("Areyousureyouwanttodeletethis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BacktoList.
        /// </summary>
        public static string BacktoList {
            get {
                return ResourceManager.GetString("BacktoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bottel_type_id.
        /// </summary>
        public static string bottel_type_id {
            get {
                return ResourceManager.GetString("bottel_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle Type.
        /// </summary>
        public static string bottle_type {
            get {
                return ResourceManager.GetString("bottle_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle Types.
        /// </summary>
        public static string BottleTypes {
            get {
                return ResourceManager.GetString("BottleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configration.
        /// </summary>
        public static string Configration {
            get {
                return ResourceManager.GetString("Configration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configration System.
        /// </summary>
        public static string ConfigrationSystem {
            get {
                return ResourceManager.GetString("ConfigrationSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact_number.
        /// </summary>
        public static string contact_number {
            get {
                return ResourceManager.GetString("contact_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creat_at.
        /// </summary>
        public static string creat_at {
            get {
                return ResourceManager.GetString("creat_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateNew.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cusmor_name.
        /// </summary>
        public static string cusmor_name {
            get {
                return ResourceManager.GetString("cusmor_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustmorReport.
        /// </summary>
        public static string CustmorReport {
            get {
                return ResourceManager.GetString("CustmorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Reports.
        /// </summary>
        public static string CustomReports {
            get {
                return ResourceManager.GetString("CustomReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to del_status.
        /// </summary>
        public static string del_status {
            get {
                return ResourceManager.GetString("del_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliveries.
        /// </summary>
        public static string Deliveries {
            get {
                return ResourceManager.GetString("Deliveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivery_date.
        /// </summary>
        public static string delivery_date {
            get {
                return ResourceManager.GetString("delivery_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Status.
        /// </summary>
        public static string DeliveryStatus {
            get {
                return ResourceManager.GetString("DeliveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Amount.
        /// </summary>
        public static string DisplayAmount {
            get {
                return ResourceManager.GetString("DisplayAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Store.
        /// </summary>
        public static string DisplayStore {
            get {
                return ResourceManager.GetString("DisplayStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emp_name.
        /// </summary>
        public static string emp_name {
            get {
                return ResourceManager.GetString("emp_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End_Date.
        /// </summary>
        public static string End_Date {
            get {
                return ResourceManager.GetString("End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expence_Dis_Amount.
        /// </summary>
        public static string Expence_Dis_Amount {
            get {
                return ResourceManager.GetString("Expence_Dis_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expence_Rev_Amount.
        /// </summary>
        public static string Expence_Rev_Amount {
            get {
                return ResourceManager.GetString("Expence_Rev_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Transaction Dismissals.
        /// </summary>
        public static string ExpenseTransactionDismissals {
            get {
                return ResourceManager.GetString("ExpenseTransactionDismissals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Transaction Revenues.
        /// </summary>
        public static string ExpenseTransactionRevenues {
            get {
                return ResourceManager.GetString("ExpenseTransactionRevenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportReport.
        /// </summary>
        public static string ExportReport {
            get {
                return ResourceManager.GetString("ExportReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fax.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstQuantity.
        /// </summary>
        public static string FirstQuantity {
            get {
                return ResourceManager.GetString("FirstQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAllSuplierStore.
        /// </summary>
        public static string GetAllSuplierStore {
            get {
                return ResourceManager.GetString("GetAllSuplierStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hire_date.
        /// </summary>
        public static string hire_date {
            get {
                return ResourceManager.GetString("hire_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income_Amount.
        /// </summary>
        public static string Income_Amount {
            get {
                return ResourceManager.GetString("Income_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Transaction.
        /// </summary>
        public static string IncomeTransaction {
            get {
                return ResourceManager.GetString("IncomeTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_update.
        /// </summary>
        public static string last_update {
            get {
                return ResourceManager.GetString("last_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location custmor.
        /// </summary>
        public static string location_cus {
            get {
                return ResourceManager.GetString("location_cus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAQAA Compan Water.
        /// </summary>
        public static string NAQAACompanWater {
            get {
                return ResourceManager.GetString("NAQAACompanWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetAmount.
        /// </summary>
        public static string NetAmount {
            get {
                return ResourceManager.GetString("NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nick.
        /// </summary>
        public static string nick {
            get {
                return ResourceManager.GetString("nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to num_bottleS_delivered.
        /// </summary>
        public static string num_bottleS_delivered {
            get {
                return ResourceManager.GetString("num_bottleS_delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number_of_bottel.
        /// </summary>
        public static string number_of_bottel {
            get {
                return ResourceManager.GetString("number_of_bottel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offer.
        /// </summary>
        public static string offer {
            get {
                return ResourceManager.GetString("offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date.
        /// </summary>
        public static string Pleaseenterdate {
            get {
                return ResourceManager.GetString("Pleaseenterdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos_type.
        /// </summary>
        public static string Pos_type {
            get {
                return ResourceManager.GetString("Pos_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity_in_Store.
        /// </summary>
        public static string quantity_in_Store {
            get {
                return ResourceManager.GetString("quantity_in_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requrirments.
        /// </summary>
        public static string Requrirments {
            get {
                return ResourceManager.GetString("Requrirments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salary.
        /// </summary>
        public static string salary {
            get {
                return ResourceManager.GetString("salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start_date.
        /// </summary>
        public static string Start_date {
            get {
                return ResourceManager.GetString("Start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suplier_name.
        /// </summary>
        public static string suplier_name {
            get {
                return ResourceManager.GetString("suplier_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suplier_type_id.
        /// </summary>
        public static string suplier_type_id {
            get {
                return ResourceManager.GetString("suplier_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suplier_type_id_all.
        /// </summary>
        public static string suplier_type_id_all {
            get {
                return ResourceManager.GetString("suplier_type_id_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suplier Names.
        /// </summary>
        public static string SuplierNames {
            get {
                return ResourceManager.GetString("SuplierNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suplier Type Prices.
        /// </summary>
        public static string SuplierTypePrices {
            get {
                return ResourceManager.GetString("SuplierTypePrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suplier Types.
        /// </summary>
        public static string SuplierTypes {
            get {
                return ResourceManager.GetString("SuplierTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Requrirments.
        /// </summary>
        public static string SystemRequrirments {
            get {
                return ResourceManager.GetString("SystemRequrirments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalAmount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction_date.
        /// </summary>
        public static string transaction_date {
            get {
                return ResourceManager.GetString("transaction_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction_type.
        /// </summary>
        public static string Transaction_type {
            get {
                return ResourceManager.GetString("Transaction_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transaction_type_id.
        /// </summary>
        public static string transaction_type_id {
            get {
                return ResourceManager.GetString("transaction_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Types.
        /// </summary>
        public static string TransactionTypes {
            get {
                return ResourceManager.GetString("TransactionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vacation_days.
        /// </summary>
        public static string vacation_days {
            get {
                return ResourceManager.GetString("vacation_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        public static string Warehouses {
            get {
                return ResourceManager.GetString("Warehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zad Alamil Company.
        /// </summary>
        public static string ZadAlamilCompany {
            get {
                return ResourceManager.GetString("ZadAlamilCompany", resourceCulture);
            }
        }
    }
}
