//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCompanySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Delivery
    {
        public int id { get; set; }
        public Nullable<int> custmor_id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]

        public Nullable<System.DateTime> delivery_date { get; set; }
        public Nullable<int> num_bottleS_delivered { get; set; }
        public int delivery_status_id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]

        public System.DateTime creat_at { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual Custmor Custmor { get; set; }
        public virtual DeliveryStatu DeliveryStatu { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
