//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCompanySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Income_Transaction
    {
        public int id { get; set; }

        //[DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        //[DataType(DataType.Date)]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> transaction_date { get; set; }
        public int transaction_type_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public int custmor_id { get; set; }
        [Required]
        public Nullable<int> quantity { get; set; }
        public Nullable<int> suplier_type_id { get; set; }
        public Nullable<int> payment_type_id { get; set; }
        public string note { get; set; }
    
        public virtual Custmor Custmor { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
        public virtual SuplierTypePrice SuplierTypePrice { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
