//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCompanySystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Warehouse
    {
        public int id { get; set; }
        public int suplier_type_id { get; set; }
        public Nullable<int> quantity { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]

        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<int> bottel_type_id { get; set; }
    
        public virtual BottleType BottleType { get; set; }
        public virtual SuplierType SuplierType { get; set; }
    }
}
