//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterCompanySystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WaterComponySystemEntities : DbContext
    {
        public WaterComponySystemEntities()
            : base("name=WaterComponySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BottleType> BottleTypes { get; set; }
        public virtual DbSet<Custmor> Custmors { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<DeliveryStatu> DeliveryStatus { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Expense_Transaction> Expense_Transaction { get; set; }
        public virtual DbSet<Income_Transaction> Income_Transaction { get; set; }
        public virtual DbSet<Payment_Type> Payment_Type { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<RoleTable> RoleTables { get; set; }
        public virtual DbSet<SuplierName> SuplierNames { get; set; }
        public virtual DbSet<SuplierType> SuplierTypes { get; set; }
        public virtual DbSet<SuplierTypePrice> SuplierTypePrices { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
